{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0750764c-907f-406e-99a1-c849eba5e865",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn.functional as F\n",
    "import numpy as np\n",
    "import cv2\n",
    "import os\n",
    "from ultralytics import YOLO\n",
    "import matplotlib.pyplot as plt\n",
    "import torchvision\n",
    "def generate_masks(N, h, w, H, W, p):\n",
    "    masks = torch.zeros(N, H, W)\n",
    "    Ch = np.floor(H/h)\n",
    "    Cw = np.floor(W/w)\n",
    "    x_up = int(Ch*(h+1))\n",
    "    y_up = int(Cw*(w+1))\n",
    "\n",
    "    for i in range(N):\n",
    "        mask = torch.zeros(h, w)\n",
    "        mask = mask.bernoulli_(p)\n",
    "        # Bilinear Interpolation\n",
    "        mask = F.interpolate(mask.unsqueeze(0).unsqueeze(0), size=(x_up, y_up), mode='bilinear', align_corners=False)\n",
    "        mask = mask.squeeze()\n",
    "        # Random Cropping with uniformly random offsets\n",
    "        x_offset = np.random.randint(0, x_up-H)\n",
    "        y_offset = np.random.randint(0, y_up-W)\n",
    "        mask = mask[x_offset:x_offset+H, y_offset:y_offset+W]\n",
    "        masks[i] = mask\n",
    "        # Saving the mask\n",
    "        cv2.imwrite('/content/drive/MyDrive/masks/mask'+str(i)+'.jpg', mask.numpy()*255)\n",
    "        if i%100==0:\n",
    "            print(i)\n",
    "\n",
    "def overlay_masks(masks_dir  , image_path):\n",
    "    image= cv2.imread(image_path)\n",
    "    image=cv2.resize(image,(640,640))\n",
    "    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "    masks = os.listdir(masks_dir)\n",
    "    image_name = image_path.split('/')[-1].split('.')[0]\n",
    "    for mask_name in masks:\n",
    "        mask_path = os.path.join(masks_dir, mask_name)\n",
    "        mask = cv2.imread(mask_path)\n",
    "        # mask is a 3 channel image, we only need one channel which is binary\n",
    "        mask = mask[:,:,0]\n",
    "        mask = mask/255\n",
    "\n",
    "        # overlay mask on image\n",
    "        overlay = image.copy()\n",
    "        overlay[:,:,0] = mask*image[:,:,0]\n",
    "        overlay[:,:,1] = mask*image[:,:,1]\n",
    "        overlay[:,:,2] = mask*image[:,:,2]\n",
    "\n",
    "        # save overlayed image\n",
    "        cv2.imwrite(f'/content/overlayed/{mask_name}',  cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))\n",
    "\n",
    "def compute_iou(boxA, boxB):\n",
    "    \"\"\"\n",
    "    Computes IoU between two bounding boxes.\n",
    "    boxA, boxB: (x1, y1, x2, y2)\n",
    "    Returns: IoU as float\n",
    "    \"\"\"\n",
    "    # Compute intersection coordinates\n",
    "    xA = max(boxA[0], boxB[0])\n",
    "    yA = max(boxA[1], boxB[1])\n",
    "    xB = min(boxA[2], boxB[2])\n",
    "    yB = min(boxA[3], boxB[3])\n",
    "\n",
    "    # Compute intersection area\n",
    "    inter_width = max(0, xB - xA)\n",
    "    inter_height = max(0, yB - yA)\n",
    "    inter_area = inter_width * inter_height\n",
    "\n",
    "    # Compute area of each box\n",
    "    boxA_area = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])\n",
    "    boxB_area = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])\n",
    "\n",
    "    # Compute union area\n",
    "    union_area = boxA_area + boxB_area - inter_area\n",
    "    if union_area == 0:\n",
    "        return 0.0\n",
    "\n",
    "    # Compute IoU\n",
    "    iou = inter_area / union_area\n",
    "    return iou"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61d76da1-d836-47e6-b815-c6e4b75b2167",
   "metadata": {},
   "outputs": [],
   "source": [
    "w = {}  # Dictionary to store max IoU per image\n",
    "overlayed_dir = \"/content/overlayed\"\n",
    "target_box=np.array([ 259.4574, 104.9096, 312.1807, 205.3037  ,   0.3423    ,       1])\n",
    "model = YOLO(\"/content/drive/MyDrive/best(1).pt\")  # Load YOLO model\n",
    "for i in range(5000):\n",
    "    # Construct file path\n",
    "    file_name = \"mask{}.jpg\".format(i)\n",
    "    file_path = os.path.join(overlayed_dir, file_name)\n",
    "\n",
    "    # Read overlayed image\n",
    "    overlayed_image = cv2.imread(file_path)\n",
    "\n",
    "    # Run YOLO model\n",
    "    result = model(file_path, verbose=False)\n",
    "\n",
    "    # Initialize max IoU for this image\n",
    "    max_iou = 0\n",
    "\n",
    "    # Print progress every 100 images\n",
    "    if i % 100 == 0:\n",
    "        print(i)\n",
    "\n",
    "    # Loop through predicted boxes\n",
    "    for box in result[0].boxes:\n",
    "\n",
    "        if box.cls.item()!=target_box[-1].item():\n",
    "            continue\n",
    "        a = box.xyxy.cpu().numpy()[0]  # Get box coordinates\n",
    "        conf = float(box.conf)          # Get confidence\n",
    "        iou = float(compute_iou(a, target_box))\n",
    "        iou=iou*conf\n",
    "        # Update max IoU\n",
    "        if iou > max_iou:\n",
    "            max_iou = iou\n",
    "\n",
    "    # Save every 50 images for tracing\n",
    "\n",
    "\n",
    "    # Store max IoU for this image\n",
    "    w[file_name] = max_iou"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8eefc0ee-7d10-457b-a04b-0f185bb4cf25",
   "metadata": {},
   "outputs": [],
   "source": [
    "weighted_mask = np.zeros((640, 640))\n",
    "\n",
    "for file_name in w.keys():\n",
    "    mask_path = os.path.join(mask_dir, file_name)\n",
    "    mask = cv2.imread(mask_path)[:, :, 0]  # Load first channel\n",
    "    mask = mask / 255  # Normalize\n",
    "    weighted_mask += w[file_name] * mask  # Weight by max IoU\n",
    "\n",
    "#weighted_mask=(weighted_mask-np.min(weighted_mask))/(np.max(weighted_mask)-np.min(weighted_mask))\n",
    "# --- Visualization ---\n",
    "file_path = \"/content/2016-08-02-wolfsburg-links-L0150--patch39.jpg\"\n",
    "img = cv2.imread(file_path)\n",
    "img = cv2.resize(img, (640, 640))\n",
    "img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "# Draw target bounding box\n",
    "\n",
    "\n",
    "# Show image with weighted mask overlay\n",
    "plt.imshow(img)\n",
    "plt.imshow(weighted_mask, cmap='jet', alpha=0.5)\n",
    "plt.axis('off')\n",
    "\n",
    "# Save result\n",
    "plt.savefig(\"/content/drise1.jpg\",\n",
    "bbox_inches=\"tight\",\n",
    "pad_inches=0\n",
    ")\n",
    "\n",
    "plt.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
